import type { Task } from "./types";

export const SEED_TASKS: Task[] = [
  {
    id: "t01",
    title: "Morning visualization",
    group: "morning",
    type: "check",
    order: 1,
    hidden: false,
    archived: false,
  },
  {
    id: "t02",
    title: "Read a story about me and a statement about me",
    group: "morning",
    type: "check",
    order: 2,
    hidden: false,
    archived: false,
  },
  {
    id: "t03",
    title: "Write a plan for 10 years, 1 year, and 1 day",
    group: "morning",
    type: "check",
    order: 3,
    hidden: false,
    archived: false,
  },
  {
    id: "t04",
    title: "Pray 10 times in the morning",
    group: "morning",
    type: "count",
    target: 10,
    order: 4,
    hidden: false,
    archived: false,
  },
  {
    id: "t05",
    title: "Look at visualization #1",
    group: "morning",
    type: "check",
    order: 5,
    hidden: false,
    archived: false,
  },
  {
    id: "t06",
    title: "Give a valuable word to someone",
    group: "body",
    type: "check",
    order: 6,
    hidden: false,
    archived: false,
  },
  {
    id: "t07",
    title: "Brush your teeth",
    group: "body",
    type: "check",
    order: 7,
    hidden: false,
    archived: false,
  },
  {
    id: "t08",
    title: "Take a shower",
    group: "body",
    type: "check",
    order: 8,
    hidden: false,
    archived: false,
  },
  {
    id: "t09",
    title: "Drink a glass of water",
    group: "body",
    type: "check",
    order: 9,
    hidden: false,
    archived: false,
  },
  {
    id: "t10",
    title: "Drink a scoop of protein",
    group: "body",
    type: "check",
    order: 10,
    hidden: false,
    archived: false,
  },
  {
    id: "t11",
    title: "Work out in the gym or do 45 minutes on your own",
    group: "body",
    type: "check",
    order: 11,
    hidden: false,
    archived: false,
  },
  {
    id: "t12",
    title: "Do all the back exercises",
    group: "body",
    type: "check",
    order: 12,
    hidden: false,
    archived: false,
  },
  {
    id: "t13",
    title: "Put cream on your fingers",
    group: "body",
    type: "check",
    order: 13,
    hidden: false,
    archived: false,
  },
  {
    id: "t14",
    title: "Do Kegel exercises with the mobile app",
    group: "body",
    type: "check",
    order: 14,
    hidden: false,
    archived: false,
  },
  {
    id: "t15",
    title: "Eat breakfast",
    group: "food",
    type: "check",
    order: 15,
    hidden: false,
    archived: false,
  },
  {
    id: "t16",
    title: "Eat cottage cheese with fruits",
    group: "food",
    type: "check",
    order: 16,
    hidden: false,
    archived: false,
  },
  {
    id: "t17",
    title: "Eat lunch",
    group: "food",
    type: "check",
    order: 17,
    hidden: false,
    archived: false,
  },
  {
    id: "t18",
    title: "Eat dinner",
    group: "food",
    type: "check",
    order: 18,
    hidden: false,
    archived: false,
  },
  {
    id: "t19",
    title: "Do my daily plans",
    group: "work",
    type: "check",
    order: 19,
    hidden: false,
    archived: false,
  },
  {
    id: "t20",
    title: "Post 3 times on social media (teach English)",
    group: "work",
    type: "count",
    target: 3,
    order: 20,
    hidden: false,
    archived: false,
  },
  {
    id: "t21",
    title:
      "Contact 3 men with successful families, businesses, and healthy marriages",
    group: "work",
    type: "count",
    target: 3,
    order: 21,
    hidden: false,
    archived: false,
  },
  {
    id: "t22",
    title:
      "Leave 10 comments on popular Ukrainian pages in Chicago (10k+ followers)",
    group: "work",
    type: "count",
    target: 10,
    order: 22,
    hidden: false,
    archived: false,
  },
  {
    id: "t23",
    title: "Repost my video on Facebook to 20 US groups",
    group: "work",
    type: "count",
    target: 20,
    order: 23,
    hidden: false,
    archived: false,
  },
  {
    id: "t24",
    title: "Contact 20 new drivers",
    group: "work",
    type: "count",
    target: 20,
    order: 24,
    hidden: false,
    archived: false,
  },
  {
    id: "t25",
    title: "Add all personal finances to Excel (income & outcome)",
    group: "work",
    type: "check",
    order: 25,
    hidden: false,
    archived: false,
  },
  {
    id: "t26",
    title: "Pray 10 times in the evening",
    group: "evening",
    type: "count",
    target: 10,
    order: 26,
    hidden: false,
    archived: false,
  },
  {
    id: "t27",
    title: "Brush teeth before going to bed",
    group: "evening",
    type: "check",
    order: 27,
    hidden: false,
    archived: false,
  },
  {
    id: "t28",
    title: "Go to bed by 10 pm",
    group: "evening",
    type: "check",
    order: 28,
    hidden: false,
    archived: false,
  },
  {
    id: "t29",
    title: "Repeat affirmations during the day",
    group: "close",
    type: "count",
    target: 1000,
    order: 29,
    hidden: false,
    archived: false,
  },
];
