headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/workspace/out"
publishOrigin = "config"
commandOrigin = "config"
command = "echo skip"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]